"""remove_isbn_field

Revision ID: 0f53a6e4e22f
Revises: 47a281ed16a2
Create Date: 2025-09-27 13:15:21.881383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f53a6e4e22f'
down_revision = '47a281ed16a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_isbn'), table_name='books')
    op.drop_column('books', 'isbn')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('isbn', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_books_isbn'), 'books', ['isbn'], unique=False)
    # ### end Alembic commands ###
